//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arackiralamaproject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCARS
    {
        public int ID { get; set; }
        public string BASLIK { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public string ACIKLAMA { get; set; }
        public string KOLTUKSAYI { get; set; }
        public string YAKIT { get; set; }
        public string VITES { get; set; }
        public string GORSEL { get; set; }
    }
}
